# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 11:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_date', models.DateTimeField(auto_now_add=True, verbose_name='Update date')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_date', models.DateTimeField(auto_now_add=True, verbose_name='Update date')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Criteria')),
            ],
        ),
        migrations.CreateModel(
            name='Rummage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_date', models.DateTimeField(auto_now_add=True, verbose_name='Update date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rummage_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.TextField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_date', models.DateTimeField(auto_now_add=True, verbose_name='Update date')),
                ('rummage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Rummage')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='rummage_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Rummage_item'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='rummage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Rummage'),
        ),
    ]
