# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rummage_item',
            name='link',
        ),
        migrations.AddField(
            model_name='rummage',
            name='url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rummage_item',
            name='url',
            field=models.TextField(default='http://www.leboncoin.fr'),
            preserve_default=False,
        ),
    ]
