# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160625_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='rummage_item',
            name='infos',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rummage_item',
            name='lbc_id',
            field=models.IntegerField(default=984889394),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rummage_item',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rummage_item',
            name='thumbnail_url',
            field=models.TextField(null=True),
        ),
    ]
