# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160707_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='rummage_item',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rummage_item',
            name='lbc_id',
            field=models.IntegerField(unique=True),
        ),
    ]
