# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160810_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.FloatField(default=0.0),
        ),
    ]
